# Generated by Django 3.1 on 2021-04-11 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(db_index=True, max_length=255)),
                ('datetime_create', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('datetime_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'cuisine.cuisine',
                'ordering': ['-datetime_create'],
            },
        ),
        migrations.CreateModel(
            name='Dishes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('image', models.ImageField(upload_to='dishes')),
                ('datetime_create', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('datetime_update', models.DateTimeField(auto_now=True)),
                ('cuisine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuisine.cuisine')),
            ],
            options={
                'verbose_name': 'cuisine.dishes',
                'ordering': ['-datetime_update'],
            },
        ),
    ]
