# Generated by Django 3.1 on 2021-04-11 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuisine', '0003_auto_20210411_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishes',
            name='image',
            field=models.ImageField(upload_to='static/dishes'),
        ),
    ]
